#**Series**

Las Series contienen un array unidimensional de datos y un array de índices.

In [1]:
import numpy as np
import pandas as pd

In [9]:
#Se crea una Serie

serie = pd.Series([1990, 1991, 1992])

print(f"SERIE\n{serie}\n")

#VALUES: Para imprimir los valores de la Serie
print(f"VALORES DE LA SERIE\n{serie.values}\n")

#VALUES: se pueden realizar otras operaciones
print(f"SUMAR VALORES DE LA SERIE\n{serie.values.sum()}\n")

#INDEX: Indices de la Serie
print(f"ÍNDICES DE LA SERIE\n{serie.index}\n")

SERIE
0    1990
1    1991
2    1992
dtype: int64

VALORES DE LA SERIE
[1990 1991 1992]

SUMAR VALORES DE LA SERIE
5973

ÍNDICES DE LA SERIE
RangeIndex(start=0, stop=3, step=1)

In [8]:
#SE DETERMINA UN INDICE PARA LA SERIE, PRIMERO SON LOS VALORES DE LA SERIE Y LUEGO LOS ÍNDICES

serie_indice = pd.Series ([1990, 1991, 1992], index=['Ana', 'Megan', 'Mariana'])
print(f"SERIE CON ÍNDICE\n{serie_indice}")

SERIE CON ÍNDICE
Ana        1990
Megan      1991
Mariana    1992
dtype: int64

In [12]:
#CREAR UNA SERIE A PARTIR DE UN DICCIONARIO

serie_diccionario = pd.Series({"Cuadrado de {}".format(i): i**2 for i in range(1,11)})

print(serie_diccionario)

Cuadrado de 1       1
Cuadrado de 2       4
Cuadrado de 3       9
Cuadrado de 4      16
Cuadrado de 5      25
Cuadrado de 6      36
Cuadrado de 7      49
Cuadrado de 8      64
Cuadrado de 9      81
Cuadrado de 10    100
dtype: int64