#**3.7 Agrupar Datos**

In [36]:
import numpy as np
import pandas as pd

In [37]:

data = pd.read_csv('https://raw.githubusercontent.com/pat-lp/Cursos-de-Python/main/Python%203/10%20-%20Manipulaci%C3%B3n%20de%20Datos%20con%20Pandas/data_celular.csv',
                   header = 0, #COLUMNAS
                   index_col = 0, #COLUMNA TOMADA COMO INDICE
                   names = ['indice', 'fecha','duracion', 'item', 'mes', 'red', 'tipo_red'],
                   parse_dates = ['fecha']
                   )

data.head()

                     fecha  duracion  item      mes       red tipo_red
indice
0      2014-10-15 06:58:00    34.429  data  2014-11      data     data
1      2014-10-15 06:58:00    13.000  call  2014-11  Vodafone   mobile
2      2014-10-15 14:46:00    23.000  call  2014-11    Meteor   mobile
3      2014-10-15 14:48:00     4.000  call  2014-11     Tesco   mobile
4      2014-10-15 17:27:00     4.000  call  2014-11     Tesco   mobile

In [39]:
#INFORMACION DEL DATAFRAME

print(f"CUANTAS FILAS TIENE EL DATAFRAME: {data['item'].count()}")
print(f"TIEMPO TOTAL EN SEGUNDOS REGISTRADO EN LLAMADAS: {data['duracion'][data['item'] == 'call'].sum()}")
print(f"CON CUANTAS REDES TELEFONICAS SE CONTACTO EN EL PERIODO 2014/11 AL 2015/03: {data['red'].nunique()}")

CUANTAS FILAS TIENE EL DATAFRAME: 830
TIEMPO TOTAL EN SEGUNDOS REGISTRADO EN LLAMADAS: 92321.0
CON CUANTAS REDES TELEFONICAS SE CONTACTO EN EL PERIODO 2014/11 AL 2015/03: 9

####**.groupby()**

Permite agrupar datos para obtener informaci√≥n.

In [40]:
data.groupby('mes').groups. values()

dict_values([Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
            ...
            220, 221, 222, 223, 224, 225, 226, 227, 229, 230],
           dtype='int64', name='indice', length=230), Int64Index([228, 231, 232, 233, 234, 235, 236, 237, 238, 239,
            ...
            377, 378, 379, 380, 382, 383, 384, 385, 387, 388],
           dtype='int64', name='indice', length=157), Int64Index([381, 386, 389, 390, 391, 392, 393, 394, 395, 396,
            ...
            583, 584, 585, 587, 588, 589, 590, 591, 592, 593],
           dtype='int64', name='indice', length=205), Int64Index([577, 586, 594, 595, 596, 597, 598, 599, 600, 601,
            ...
            719, 720, 721, 722, 723, 724, 725, 726, 727, 728],
           dtype='int64', name='indice', length=137), Int64Index([729, 730, 731, 732, 733, 734, 735, 736, 737, 738,
            ...
            820, 821, 822, 823, 824, 825, 826, 827, 828, 829],
           dtype='int64', name='indice', length=101)])

In [41]:
print("CANTIDAD DE ENTRADAS POR MES SEGREGADAS EN LLAMADAS, SMS Y DATOS")
print(data.groupby(['mes','item'])['duracion'].count())

CANTIDAD DE ENTRADAS POR MES SEGREGADAS EN LLAMADAS, SMS Y DATOS
mes      item
2014-11  call    107
         data     29
         sms      94
2014-12  call     79
         data     30
         sms      48
2015-01  call     88
         data     31
         sms      86
2015-02  call     67
         data     31
         sms      39
2015-03  call     47
         data     29
         sms      25
Name: duracion, dtype: int64

In [42]:
print("DURACION TOTAL DE LLAMADAS REALIZADAS A CADA UNA DE LAS OPERADORES ES:")
data[data['item'] == 'call'].groupby('red')['duracion'].sum()

DURACION TOTAL DE LLAMADAS REALIZADAS A CADA UNA DE LAS OPERADORES ES:

red
Meteor        7200.0
Tesco        13828.0
Three        36464.0
Vodafone     14621.0
landline     18433.0
voicemail     1775.0
Name: duracion, dtype: float64

In [43]:
print("CUANTAS LLAMADAS, SMS Y DATOS SON ENVIADOS A CADA OPERADORA POR MES")
data.groupby(['mes','tipo_red'])['fecha'].count()

CUANTAS LLAMADAS, SMS Y DATOS SON ENVIADOS A CADA OPERADORA POR MES

mes      tipo_red
2014-11  data          29
         landline       5
         mobile       189
         special        1
         voicemail      6
2014-12  data          30
         landline       7
         mobile       108
         voicemail      8
         world          4
2015-01  data          31
         landline      11
         mobile       160
         voicemail      3
2015-02  data          31
         landline       8
         mobile        90
         special        2
         voicemail      6
2015-03  data          29
         landline      11
         mobile        54
         voicemail      4
         world          3
Name: fecha, dtype: int64